import threeSrc from "../vendor/three.min.js?raw";
// Generated by `npm run build:runtime` from renderer/standalone-entry.ts +
// renderer/core/* — the same model/layout/style modules the app renderer uses.
import runtimeSrc from "../generated/standalone-runtime.js?raw";
import type { GraphDocument } from "../types/graph";
import type { GraphTheme } from "../renderer/hybridGraph";
import type { GraphShape } from "../renderer/core/layout";

export interface StandaloneConfig {
  theme: GraphTheme;
  palette: string[];
  labelMode: string;
  labelSize: number;
  clickAction: string;
  // Layout silhouette; optional so pre-shape callers/payloads stay valid.
  shape?: GraphShape;
}

export interface StandaloneOptions {
  title?: string;
  /**
   * Load Three.js from a CDN (`<script src>`) instead of inlining ~670 KB of
   * it. Used for the iframe embed so the snippet is small enough to actually
   * paste into a host page; the downloadable HTML keeps Three inlined (offline).
   */
  cdnThree?: boolean;
}

// Pinned to the bundled Three version; this CDN file is the byte-identical UMD
// build that exposes the global `THREE` the runtime relies on. SRI pins the
// exact bytes so a CDN compromise can't inject code into embedded graphs.
const THREE_CDN =
  "https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.min.js";
const THREE_SRI =
  "sha384-qOkzR5Ke/XkQxuGVJ9hpFEpDlcoLtWwVYhnJf06cLIZa2vaIptSqaubivErzmD5O";

const closeScript = (s: string) => s.replace(/<\/script>/gi, "<\\/script>");

export function buildStandaloneHtml(
  graph: GraphDocument,
  config: StandaloneConfig,
  opts: StandaloneOptions = {},
): string {
  const title = opts.title || "Constella graph";
  // Root = node with no parent (depth 0); shown as the chart title.
  const rootName =
    graph.nodes.find((n) => !n.parent)?.name ?? graph.nodes[0]?.name ?? "";
  const t = config.theme;
  const payload = JSON.stringify({ data: graph, config }).replace(/</g, "\\u003c");

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${escapeHtml(title)}</title>
<style>
  html,body{margin:0;height:100%;overflow:hidden;background:${t.bg};color:${t.text};
    font-family:system-ui,-apple-system,"Segoe UI",Roboto,sans-serif;-webkit-font-smoothing:antialiased}
  #app{position:relative;display:flex;flex-direction:column;width:100vw;height:100vh;overflow:hidden}
  #chart-title{flex:none;margin:0;text-align:center;font-weight:600;letter-spacing:-0.01em;
    font-size:clamp(16px,2.2vw,22px);padding:clamp(16px,2.4vw,24px) 16px clamp(20px,3vw,32px)}
  #stage{position:relative;flex:1 1 auto;min-height:0}
  #scene{position:absolute;inset:0;z-index:1}
  #scene canvas{display:block;cursor:default;touch-action:none}
  #labels{position:absolute;inset:0;pointer-events:none;z-index:2;overflow:hidden}
  .nlabel{position:absolute;white-space:pre;font-weight:500;
    line-height:1.25;padding:1px 5px;border-radius:5px;will-change:left,top,opacity}
  #tooltip{position:absolute;z-index:5;pointer-events:auto;min-width:180px;max-width:280px;
    border-radius:12px;padding:11px 13px;background:${t.surface};border:1px solid ${t.border};
    box-shadow:0 12px 30px rgba(0,0,0,.18);opacity:0;transform:translateY(4px);
    transition:opacity .12s ease,transform .12s ease}
  #tooltip:not(.show){pointer-events:none}
  #tooltip.show{opacity:1;transform:translateY(0)}
  .tt-medialink{display:block;text-decoration:none}
  .tt-media{display:block;width:calc(100% + 26px);margin:-11px -13px 9px;max-height:150px;
    object-fit:cover;border-radius:12px 12px 0 0;border-bottom:1px solid ${t.border}}
  .tt-name{font-size:14px;font-weight:600;margin-bottom:2px}
  .tt-path{font-size:11px;color:${t.muted};margin-bottom:8px}
  .tt-meta{font-size:11px;color:${t.muted};display:flex;flex-direction:column;gap:3px}
  .tt-meta b{color:${t.text};font-weight:600}
  .tt-url{display:block;font-size:11px;color:${t.accent};margin-top:8px;word-break:break-all;text-decoration:none}
  .tt-url:hover{text-decoration:underline}
  .tt-refs{margin-top:8px;display:flex;flex-direction:column;gap:2px}
  .tt-refs-label{font-size:10px;text-transform:uppercase;letter-spacing:.04em;color:${t.muted};margin-bottom:2px}
  .tt-ref{font-size:11px;color:${t.accent}}
  .hg-legend{position:absolute;left:clamp(12px,1.8vw,26px);top:50%;transform:translateY(-50%);z-index:3;
    max-width:min(300px,36%);max-height:82%;overflow-y:auto;padding:12px 14px;border-radius:10px;
    background:${t.surface};border:1px solid ${t.border};box-shadow:0 12px 30px rgba(0,0,0,.18);font-size:12px;line-height:1.3}
  .hg-legend__title{font-size:11px;font-weight:600;letter-spacing:.04em;text-transform:uppercase;color:${t.muted};margin-bottom:9px}
  .hg-legend__list{list-style:none;margin:0;padding:0;display:grid;grid-template-columns:auto auto minmax(0,1fr);column-gap:6px;row-gap:7px;align-items:baseline}
  .hg-legend__row{display:contents}
  .hg-legend__from{color:${t.text}}
  .hg-legend__arrow{color:${t.muted}}
  .hg-legend__to{color:${t.accent};font-weight:500}
  @media (prefers-reduced-motion: reduce){#tooltip{transition:none}}
</style>
</head>
<body>
<div id="app">${rootName ? `<div id="chart-title">${escapeHtml(rootName)}</div>` : ""}<div id="stage"><div id="scene"></div><div id="labels"></div><div id="tooltip"></div></div></div>
${opts.cdnThree ? `<script src="${THREE_CDN}" integrity="${THREE_SRI}" crossorigin="anonymous"></script>` : `<script>${closeScript(threeSrc)}</script>`}
<script>window.__GRAPH__=${payload};</script>
<script>${closeScript(runtimeSrc)}</script>
</body>
</html>`;
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
